http:
  port: "8081"
  
sfdc:
  username: "jonas@seedtech.ph"
  password: "salesforcejnas.auG24@"
  token: "Oh8i1TGGEUiXeWQd9Uvvvqmk"
  
file:
  accountsDir: "/Users/nexseed/Documents/Projects/Mulesoft_course/APDevFundamentals_studentFiles_SP_13oct2023/resources"
  
db:
  host: "mudb.mule-training.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"